// Fill out your copyright notice in the Description page of Project Settings.


#include "MainBountyClass.h"

void AMainBountyClass::IncrementBountyCheckpoint()
{
	Super::IncrementBountyCheckpoint();
	FString TipToDisplay = "";
	if (!Completed) TipToDisplay = BountyCheckpoints[0]->GetCheckpointTip();
	Cast<AEndlessVendettaCharacter>(GetWorld()->GetFirstPlayerController()->GetPawn())->CheckpointCompletedUI(TipToDisplay, Completed);
}


void AMainBountyClass::SpawnAmmoDrops()
{
	UE_LOG(LogTemp, Display, TEXT("Bought Ammo Drops, but its not implemented yet"));
	// FActorSpawnParameters SpawnParameters;
	// SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
	// for (FTransform Spawn : AmmoDropSpawnTransforms)
	// {
	// 	GetWorld()->SpawnActor<AActor>(AmmoDropClass, Spawn.GetLocation(), Spawn.GetRotation().Rotator(), SpawnParameters);
	// }
}

void AMainBountyClass::SpawnHealthDrops()
{
	UE_LOG(LogTemp, Display, TEXT("Bought Health Drops, but its not implemented yet"));
	// FActorSpawnParameters SpawnParameters;
	// SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
	// for (FTransform Spawn : HealthDropSpawnTransforms)
	// {
	// 	GetWorld()->SpawnActor<AActor>(HealthDropClass, Spawn.GetLocation(), Spawn.GetRotation().Rotator(), SpawnParameters);
	// }
}