// Fill out your copyright notice in the Description page of Project Settings.


#include "ExampleCombatClass.h"

void AExampleCombatClass::BeginPlay()
{
	Super::BeginPlay();
	
	SetActorTickEnabled(false);
}


void AExampleCombatClass::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	UE_LOG(LogTemp, Warning, TEXT("Example Combat is being used..."));
}

void AExampleCombatClass::Activate()
{
	if (GadgetCantBeUsed()) return;

	Super::Activate();
	SetActorTickEnabled(true);
}

void AExampleCombatClass::FinishedUsing()
{
	SetActorTickEnabled(false);

	Super::FinishedUsing();
}