// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "BaseWeaponClass.h"
#include "ShotgunClass.generated.h"

/**
 * 
 */
UCLASS()
class ENDLESSVENDETTA_API AShotgunClass : public ABaseWeaponClass
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AShotgunClass();

	//How far apart the bullets will be to eachother when shot with a shotgun
	UPROPERTY(EditAnywhere, Category = "Weapon")
	FVector ShotgunBulletSpread;

protected:
	virtual void Fire() override;

	virtual void BeginPlay() override;
	
};
