// Fill out your copyright notice in the Description page of Project Settings.


#include "SilencerAttachmentClass.h"


// Sets default values for this component's properties
USilencerAttachmentClass::USilencerAttachmentClass()
{
	// Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
	// off to improve performance if you don't need them.
	PrimaryComponentTick.bCanEverTick = true;

	// ...
}


// Called when the game starts
void USilencerAttachmentClass::BeginPlay()
{
	Super::BeginPlay();

	// ADD THE LOGIC HERE LATER AFTER DEMO TO ACTUALLY MAKE THE GUN "SILENT" EVEN THO WE HAVE NO AUDIO IN THE GAME.
	
}


// Called every frame
void USilencerAttachmentClass::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// ...
}

