// Fill out your copyright notice in the Description page of Project Settings.


#include "WeaponItemClass.h"


// Sets default values
AWeaponItemClass::AWeaponItemClass()
{
	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
}

// Called when the game starts or when spawned
void AWeaponItemClass::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void AWeaponItemClass::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

//Called from WeaponInventory actor component class
void AWeaponItemClass::Equip()
{
	GetWorld();
	UE_LOG(LogTemp, Display, TEXT("World Player is in: %s"), GetWorld());
}

//Called from WeaponInventory actor component class
void AWeaponItemClass::Unequip(ABaseWeaponClass* PickedUpWeapon)
{
	//same as equip but 
}

