// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "WeaponItemClass.generated.h"

class ABaseWeaponClass;

UCLASS()
class ENDLESSVENDETTA_API AWeaponItemClass : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AWeaponItemClass();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	UFUNCTION()
	void Equip();

	UFUNCTION()
	void Unequip(ABaseWeaponClass* PickedUpWeapon);
	
};
