// Fill out your copyright notice in the Description page of Project Settings.


#include "ExampleReconClass.h"

void AExampleReconClass::BeginPlay()
{
	Super::BeginPlay();
	SetActorTickEnabled(false);
}


void AExampleReconClass::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	UE_LOG(LogTemp, Warning, TEXT("Example Recon is being used..."));
}

void AExampleReconClass::Activate()
{
	if (GadgetCantBeUsed()) return;

	Super::Activate();
	SetActorTickEnabled(true);
}

void AExampleReconClass::FinishedUsing()
{
	SetActorTickEnabled(false);

	Super::FinishedUsing();
}


