// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "EndlessVendetta/EndlessVendettaCharacter.h"
#include "EndlessVendetta/InteractionInterface.h"
#include "GameFramework/Actor.h"
#include "WeaponWorkbenchClass.generated.h"

UCLASS()
class ENDLESSVENDETTA_API AWeaponWorkbenchClass : public AActor, public IInteractionInterface
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	AWeaponWorkbenchClass();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	void Interact() override;
	void InteractPrompt() override;

	UFUNCTION(BlueprintImplementableEvent)
	void WorkbenchUI();

	AEndlessVendettaCharacter* PlayerCharacterRef;
};
