// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/SceneComponent.h"
#include "EndlessVendetta/WeaponSystem/BaseWeaponClass.h"
#include "SilencerAttachmentClass.generated.h"


UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class ENDLESSVENDETTA_API USilencerAttachmentClass : public USceneComponent
{
	GENERATED_BODY()

public:
	// Sets default values for this component's properties
	USilencerAttachmentClass();

protected:
	// Called when the game starts
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	UPROPERTY(EditAnywhere)
	UStaticMeshComponent* SilencerMesh;

	void NoiseReduction();

	ABaseWeaponClass* BaseWeaponClass;
};
