// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "DroppableWall.generated.h"

UCLASS()
class ENDLESSVENDETTA_API ADroppableWall : public AActor
{
	GENERATED_BODY()

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Sets default values for this actor's properties
	ADroppableWall();
	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	UFUNCTION(BlueprintImplementableEvent)
	void WallToCounterTimeline();

	UFUNCTION(BlueprintImplementableEvent)
	void DropWallFullyTimeline();

};
